2019-03-02 12:59:03.900 [error] <0.1301.0> Supervisor 'Elixir.ElasticConsumer.Supervisor' had child 'Elixir.ElasticConsumer' started with 'Elixir.ElasticConsumer':start_link() at undefined exit with reason {'EXIT',{undef,[{'Elixir.ElasticConsumer',start_link,[],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,349}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1157}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,315}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,...},...]}]}} in context start_error
2019-03-02 13:00:27.766 [error] <0.300.0>@Elixir.ElasticConsumer:init Supervisor 'Elixir.ElasticConsumer.Supervisor' had child 'Elixir.ElasticConsumer' started with 'Elixir.ElasticConsumer':start_link() at undefined exit with reason call to undefined function 'Elixir.ElasticConsumer':init([{name,'Elixir.ElasticConsumer'}]) in context start_error
2019-03-02 13:01:00.064 [error] <0.301.0>@gen_server:init_it:366 CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: bad return value: [{queue,<<"tweets">>},{exchange,<<"twitter">>},{routing_key,<<>>},{prefetch_count,<<"10">>},{uri,<<"amqp://user:bitnami@localhost:5672">>}] in gen_server:init_it/6 line 366
2019-03-22 00:34:34.963 [error] <0.304.0>@Elixir.URI:parse:445 CRASH REPORT Process <0.304.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.URI':parse(nil) line 445
2019-03-22 00:35:53.556 [error] <0.304.0>@Elixir.URI:parse:445 CRASH REPORT Process <0.304.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.URI':parse(nil) line 445
2019-03-22 00:36:59.174 [error] <0.333.0> Supervisor 'Elixir.ElasticConsumer.Supervisor' had child 'Elixir.ElasticConsumer' started with 'Elixir.ElasticConsumer':start_link() at undefined exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"you must merge onto an absolute URI">>} in 'Elixir.URI':merge/2 line 551 in context start_error
2019-04-14 17:53:50.214 [error] <0.304.0>@Elixir.AMQP.Connection:open:75 CRASH REPORT Process <0.304.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.AMQP.Connection':open(nil) line 75
2019-04-14 17:53:50.218 [error] <0.303.0>@Elixir.AMQP.Connection:open:75 Supervisor 'Elixir.ElasticConsumer.Supervisor' had child 'Elixir.ElasticConsumer' started with 'Elixir.ElasticConsumer':start_link() at undefined exit with reason no function clause matching 'Elixir.AMQP.Connection':open(nil) line 75 in context start_error
2019-04-14 17:53:50.218 [error] <0.301.0> CRASH REPORT Process <0.301.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.ElasticConsumer',{function_clause,[{'Elixir.AMQP.Connection',open,[nil],[{file,"lib/amqp/connection.ex"},{line,75}]},{'Elixir.GenRMQ.Consumer',get_connection,1,[{file,"lib/consumer.ex"},{line,330}]},{'Elixir.GenRMQ.Consumer',init,1,[{file,"lib/consumer.ex"},{line,222}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}}},...} in application_master:init/4 line 138
2019-04-23 00:59:25.724 [error] <0.293.0> CRASH REPORT Process <0.293.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-exchange' for queue 'create_user' in vhost '/': received 'user.deadletter' but current is 'seraph.deadletter'">>}},{gen_server,call,[<0.308.0>,{call,{'queue.declare',0,<<"create_user">>,false,true,false,false,false,[{<<"x-dead-letter-exchange">>,longstr,<<"user.deadletter">>}]},none,<0.293.0>},60000]}} in gen_server:call/3 line 223
2019-04-26 09:39:58.106 [error] <0.323.0>@Elixir.GenRMQ.Consumer:terminate:295 gen_server 'Elixir.ElasticConsumer' terminated with reason: no function clause matching 'Elixir.GenRMQ.Consumer':terminate({{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for excha...">>}},...}, #{config => [{queue,<<"create_user">>},{exchange,<<"seraph">>},{exchange_type,<<"fanout">>},{routing_key,...},...],...}) line 295
2019-04-26 09:39:58.114 [error] <0.323.0>@Elixir.GenRMQ.Consumer:terminate:295 CRASH REPORT Process 'Elixir.ElasticConsumer' with 0 neighbours crashed with reason: no function clause matching 'Elixir.GenRMQ.Consumer':terminate({{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for excha...">>}},...}, #{config => [{queue,<<"create_user">>},{exchange,<<"seraph">>},{exchange_type,<<"fanout">>},{routing_key,...},...],...}) line 295
2019-04-26 09:39:58.114 [error] <0.322.0>@Elixir.GenRMQ.Consumer:terminate:295 Supervisor 'Elixir.ElasticConsumer.Supervisor' had child 'Elixir.ElasticConsumer' started with 'Elixir.ElasticConsumer':start_link() at <0.323.0> exit with reason no function clause matching 'Elixir.GenRMQ.Consumer':terminate({{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for excha...">>}},...}, #{config => [{queue,<<"create_user">>},{exchange,<<"seraph">>},{exchange_type,<<"fanout">>},{routing_key,...},...],...}) line 295 in context child_terminated
2019-04-26 09:49:03.016 [error] <0.323.0>@Elixir.GenRMQ.Consumer:terminate:295 gen_server 'Elixir.ElasticConsumer' terminated with reason: no function clause matching 'Elixir.GenRMQ.Consumer':terminate({{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for excha...">>}},...}, #{config => [{queue,<<"create_user">>},{exchange,<<"seraph">>},{exchange_type,<<"fanout">>},{routing_key,...},...],...}) line 295
2019-04-26 09:49:03.025 [error] <0.323.0>@Elixir.GenRMQ.Consumer:terminate:295 CRASH REPORT Process 'Elixir.ElasticConsumer' with 0 neighbours crashed with reason: no function clause matching 'Elixir.GenRMQ.Consumer':terminate({{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for excha...">>}},...}, #{config => [{queue,<<"create_user">>},{exchange,<<"seraph">>},{exchange_type,<<"fanout">>},{routing_key,...},...],...}) line 295
2019-04-26 09:49:03.026 [error] <0.322.0>@Elixir.GenRMQ.Consumer:terminate:295 Supervisor 'Elixir.ElasticConsumer.Supervisor' had child 'Elixir.ElasticConsumer' started with 'Elixir.ElasticConsumer':start_link() at <0.323.0> exit with reason no function clause matching 'Elixir.GenRMQ.Consumer':terminate({{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for excha...">>}},...}, #{config => [{queue,<<"create_user">>},{exchange,<<"seraph">>},{exchange_type,<<"fanout">>},{routing_key,...},...],...}) line 295 in context child_terminated
2019-04-26 20:03:05.434 [error] <0.299.0> gen_server <0.299.0> terminated with reason: socket_closed_unexpectedly
2019-04-26 20:03:05.439 [error] <0.299.0> CRASH REPORT Process <0.299.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2019-04-26 20:03:05.439 [error] <0.297.0> Supervisor {<0.297.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.298.0>, {amqp_params_network,<<"user">>,<<"bitnami">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<a..>,...],...}) at <0.299.0> exit with reason socket_closed_unexpectedly in context child_terminated
2019-04-26 20:03:05.439 [error] <0.297.0> Supervisor {<0.297.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.298.0>, {amqp_params_network,<<"user">>,<<"bitnami">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<a..>,...],...}) at <0.299.0> exit with reason reached_max_restart_intensity in context shutdown
